r"""Critical bounds for the CUSUM and CUSUM-of-squares stability tests.

Both tests of Brown, Durbin & Evans (1975) compare a path built from the
recursive residuals against a pair of boundaries. Crossing them is the
signal of parameter instability.

CUSUM
-----
Under the null of constant parameters, :math:`W_t` is approximately a
Brownian motion, and the test uses the pair of straight lines

.. math::

    \pm \left[ a\sqrt{T-k} + \frac{2a(t-k)}{\sqrt{T-k}} \right]

The coefficient :math:`a` solves the crossing-probability equation of
Brown, Durbin & Evans (1975, §2.3): it is the value for which a Brownian
motion crosses those lines with probability ``alpha``. Only three levels
were tabulated, and only those three are served here.

CUSUM of squares
----------------
The bands are :math:`E(S_t) \pm c_0` with :math:`E(S_t) = (t-k)/(T-k)`.
The value of :math:`c_0` depends on the number of recursive residuals
``n = T - k`` and on the level.

``c_0`` is obtained by simulation rather than transcription. This is not
a fallback: the statistic is genuinely distribution-free. If the
recursive residuals are i.i.d. :math:`N(0, \sigma^2)`, then

.. math::

    S_t = \frac{\sum_{s \le t} w_s^2}{\sum_{s \le n} w_s^2}

does not depend on :math:`\sigma^2` — it is a ratio of partial sums of
i.i.d. :math:`\chi^2_1` variables. The law of
:math:`\max_t |S_t - t/n|` therefore depends on ``n`` alone and can be
simulated exactly, to any precision.

The simulated values were cross-checked against their own asymptotic
limit: :math:`\sqrt{n/2}\,c_0` converges to the Kolmogorov quantile,
since :math:`S_t - t/n` behaves like a Brownian bridge of scale
:math:`\sqrt{2/n}` (the variance of a :math:`\chi^2_1` is 2). The ratio
rises monotonically to 0.98 at ``n = 1000``. See ``PROVENANCE.md``.

References
----------
.. [1] Brown, R. L., Durbin, J. & Evans, J. M. (1975). Techniques for
       testing the constancy of regression relationships over time.
       *Journal of the Royal Statistical Society B*, 37(2), 149-192.
"""

from __future__ import annotations

import warnings

import numpy as np

from pyardl.exceptions import PyardlMethodologyWarning

__all__ = ["cusum_a", "cusumsq_c0", "CUSUM_A", "C0_GRID"]

#: Coefficient of the CUSUM boundary lines, by significance level.
#: Brown, Durbin & Evans (1975), §2.3. Only these three levels exist.
CUSUM_A: dict[float, float] = {0.10: 0.850, 0.05: 0.948, 0.01: 1.143}

_SUPPORTED_ALPHAS = (0.10, 0.05, 0.01)

# --- Everything below is GENERATED by validation/spec26_cusumsq_c0.py ---
# Simulation parameters: n_sims=200000, seed=20260802 (+n per grid point),
# chunk=20000, alphas=(0.10, 0.05, 0.01). Do not edit by hand: regenerate.
_C0_TABLE: dict[int, dict[float, float]] = {
    4: {0.1: 0.522377, 0.05: 0.603427, 0.01: 0.698663},
    5: {0.1: 0.515947, 0.05: 0.570358, 0.01: 0.688225},
    6: {0.1: 0.488531, 0.05: 0.553094, 0.01: 0.656834},
    7: {0.1: 0.470925, 0.05: 0.527014, 0.01: 0.634113},
    8: {0.1: 0.453243, 0.05: 0.508191, 0.01: 0.612105},
    9: {0.1: 0.437045, 0.05: 0.491983, 0.01: 0.593231},
    10: {0.1: 0.422437, 0.05: 0.473743, 0.01: 0.573887},
    11: {0.1: 0.408599, 0.05: 0.458751, 0.01: 0.554035},
    12: {0.1: 0.396641, 0.05: 0.445181, 0.01: 0.537884},
    13: {0.1: 0.384922, 0.05: 0.431693, 0.01: 0.524085},
    14: {0.1: 0.374561, 0.05: 0.421288, 0.01: 0.511403},
    15: {0.1: 0.366263, 0.05: 0.410689, 0.01: 0.496890},
    16: {0.1: 0.356555, 0.05: 0.399803, 0.01: 0.484053},
    17: {0.1: 0.348591, 0.05: 0.390415, 0.01: 0.473708},
    18: {0.1: 0.340553, 0.05: 0.381664, 0.01: 0.461595},
    19: {0.1: 0.333329, 0.05: 0.374168, 0.01: 0.454255},
    20: {0.1: 0.327968, 0.05: 0.367401, 0.01: 0.444379},
    21: {0.1: 0.320962, 0.05: 0.359542, 0.01: 0.435244},
    22: {0.1: 0.314876, 0.05: 0.352596, 0.01: 0.429154},
    23: {0.1: 0.309585, 0.05: 0.347220, 0.01: 0.420208},
    24: {0.1: 0.303468, 0.05: 0.339544, 0.01: 0.412569},
    25: {0.1: 0.299100, 0.05: 0.334829, 0.01: 0.406648},
    26: {0.1: 0.293418, 0.05: 0.329533, 0.01: 0.399942},
    27: {0.1: 0.289094, 0.05: 0.324118, 0.01: 0.392122},
    28: {0.1: 0.284921, 0.05: 0.319023, 0.01: 0.387246},
    29: {0.1: 0.280784, 0.05: 0.314335, 0.01: 0.381028},
    30: {0.1: 0.276899, 0.05: 0.310130, 0.01: 0.374715},
    31: {0.1: 0.273639, 0.05: 0.306309, 0.01: 0.371030},
    32: {0.1: 0.270078, 0.05: 0.301613, 0.01: 0.364686},
    33: {0.1: 0.266387, 0.05: 0.297897, 0.01: 0.360344},
    34: {0.1: 0.262217, 0.05: 0.294079, 0.01: 0.354031},
    35: {0.1: 0.258576, 0.05: 0.289809, 0.01: 0.351182},
    36: {0.1: 0.256759, 0.05: 0.287045, 0.01: 0.346287},
    37: {0.1: 0.253691, 0.05: 0.283463, 0.01: 0.343153},
    38: {0.1: 0.250270, 0.05: 0.279864, 0.01: 0.338714},
    39: {0.1: 0.247564, 0.05: 0.277446, 0.01: 0.336100},
    40: {0.1: 0.244688, 0.05: 0.273714, 0.01: 0.330949},
    42: {0.1: 0.239275, 0.05: 0.267711, 0.01: 0.323403},
    44: {0.1: 0.234750, 0.05: 0.262656, 0.01: 0.316802},
    46: {0.1: 0.230468, 0.05: 0.257806, 0.01: 0.311597},
    48: {0.1: 0.225874, 0.05: 0.252613, 0.01: 0.305266},
    50: {0.1: 0.221410, 0.05: 0.247407, 0.01: 0.299147},
    52: {0.1: 0.218355, 0.05: 0.244217, 0.01: 0.295781},
    54: {0.1: 0.214556, 0.05: 0.239919, 0.01: 0.290269},
    56: {0.1: 0.210925, 0.05: 0.236047, 0.01: 0.285070},
    58: {0.1: 0.208214, 0.05: 0.232670, 0.01: 0.279900},
    60: {0.1: 0.204103, 0.05: 0.227884, 0.01: 0.276725},
    62: {0.1: 0.201363, 0.05: 0.225112, 0.01: 0.272104},
    64: {0.1: 0.198754, 0.05: 0.221582, 0.01: 0.267809},
    66: {0.1: 0.195892, 0.05: 0.219314, 0.01: 0.265179},
    68: {0.1: 0.193233, 0.05: 0.215631, 0.01: 0.260573},
    70: {0.1: 0.190862, 0.05: 0.213009, 0.01: 0.256995},
    72: {0.1: 0.188351, 0.05: 0.209968, 0.01: 0.253898},
    74: {0.1: 0.186626, 0.05: 0.208319, 0.01: 0.251301},
    76: {0.1: 0.183645, 0.05: 0.204974, 0.01: 0.246909},
    78: {0.1: 0.181303, 0.05: 0.202360, 0.01: 0.243579},
    80: {0.1: 0.179418, 0.05: 0.200437, 0.01: 0.241398},
    85: {0.1: 0.174688, 0.05: 0.194826, 0.01: 0.235087},
    90: {0.1: 0.169921, 0.05: 0.188992, 0.01: 0.227780},
    95: {0.1: 0.165488, 0.05: 0.184509, 0.01: 0.223970},
    100: {0.1: 0.161926, 0.05: 0.180672, 0.01: 0.218106},
    105: {0.1: 0.158376, 0.05: 0.176302, 0.01: 0.213382},
    110: {0.1: 0.154906, 0.05: 0.172835, 0.01: 0.207941},
    115: {0.1: 0.151653, 0.05: 0.169231, 0.01: 0.204788},
    120: {0.1: 0.148841, 0.05: 0.165924, 0.01: 0.200145},
    125: {0.1: 0.146096, 0.05: 0.162884, 0.01: 0.196473},
    130: {0.1: 0.143160, 0.05: 0.159538, 0.01: 0.192830},
    135: {0.1: 0.140851, 0.05: 0.157024, 0.01: 0.189501},
    140: {0.1: 0.138267, 0.05: 0.154039, 0.01: 0.186131},
    145: {0.1: 0.135998, 0.05: 0.151628, 0.01: 0.183117},
    150: {0.1: 0.133954, 0.05: 0.149214, 0.01: 0.180060},
    160: {0.1: 0.130007, 0.05: 0.144685, 0.01: 0.174356},
    170: {0.1: 0.126371, 0.05: 0.140758, 0.01: 0.169300},
    180: {0.1: 0.123053, 0.05: 0.137336, 0.01: 0.165561},
    190: {0.1: 0.119655, 0.05: 0.133522, 0.01: 0.160821},
    200: {0.1: 0.117106, 0.05: 0.130549, 0.01: 0.156949},
    210: {0.1: 0.114223, 0.05: 0.127427, 0.01: 0.153220},
    220: {0.1: 0.111812, 0.05: 0.124507, 0.01: 0.150013},
    230: {0.1: 0.109539, 0.05: 0.121951, 0.01: 0.147181},
    240: {0.1: 0.107038, 0.05: 0.119402, 0.01: 0.143233},
    250: {0.1: 0.104927, 0.05: 0.117014, 0.01: 0.140809},
    260: {0.1: 0.103044, 0.05: 0.114834, 0.01: 0.138230},
    270: {0.1: 0.101049, 0.05: 0.112583, 0.01: 0.135734},
    280: {0.1: 0.099593, 0.05: 0.110838, 0.01: 0.133194},
    290: {0.1: 0.098071, 0.05: 0.109066, 0.01: 0.131263},
    300: {0.1: 0.096502, 0.05: 0.107536, 0.01: 0.129501},
    350: {0.1: 0.089480, 0.05: 0.099581, 0.01: 0.120238},
    400: {0.1: 0.083923, 0.05: 0.093250, 0.01: 0.112562},
    450: {0.1: 0.079200, 0.05: 0.088243, 0.01: 0.106486},
    500: {0.1: 0.075145, 0.05: 0.083841, 0.01: 0.101182},
    550: {0.1: 0.071896, 0.05: 0.079927, 0.01: 0.096288},
    600: {0.1: 0.068904, 0.05: 0.076756, 0.01: 0.092196},
    650: {0.1: 0.066326, 0.05: 0.073809, 0.01: 0.088758},
    700: {0.1: 0.063886, 0.05: 0.071062, 0.01: 0.085496},
    750: {0.1: 0.061758, 0.05: 0.068659, 0.01: 0.082680},
    800: {0.1: 0.059791, 0.05: 0.066547, 0.01: 0.080156},
    850: {0.1: 0.058087, 0.05: 0.064533, 0.01: 0.077863},
    900: {0.1: 0.056503, 0.05: 0.062873, 0.01: 0.075003},
    950: {0.1: 0.055031, 0.05: 0.061162, 0.01: 0.073564},
    1000: {0.1: 0.053606, 0.05: 0.059558, 0.01: 0.071398},
}

#: Sample sizes ``n = T - k`` covered by the simulated table.
C0_GRID: tuple[int, ...] = tuple(sorted(_C0_TABLE))

_N_MIN = C0_GRID[0]
_N_MAX = C0_GRID[-1]


def _check_alpha(alpha: float) -> float:
    for a in _SUPPORTED_ALPHAS:
        if abs(alpha - a) < 1e-12:
            return a
    raise ValueError(
        f"alpha={alpha} is not available. The CUSUM and CUSUM-of-squares "
        f"bounds exist at {_SUPPORTED_ALPHAS} only."
    )


def cusum_a(alpha: float = 0.05) -> float:
    """Coefficient of the CUSUM boundary lines.

    Parameters
    ----------
    alpha : float, default 0.05
        Significance level. One of 0.10, 0.05, 0.01.

    Returns
    -------
    float
        The coefficient ``a`` entering ``+/- [a*sqrt(T-k) +
        2*a*(t-k)/sqrt(T-k)]``.

    Raises
    ------
    ValueError
        If ``alpha`` is not one of the three tabulated levels. No
        neighbouring level is silently substituted.

    Examples
    --------
    >>> from pyardl.critical_values.bde1975 import cusum_a
    >>> cusum_a(0.05)
    0.948
    """
    return CUSUM_A[_check_alpha(alpha)]


def cusumsq_c0(n: int, alpha: float = 0.05) -> float:
    """Half-width of the CUSUM-of-squares band.

    Parameters
    ----------
    n : int
        Number of recursive residuals, ``n = T - k``.
    alpha : float, default 0.05
        Significance level. One of 0.10, 0.05, 0.01.

    Returns
    -------
    float
        The value ``c0`` such that the band is ``(t-k)/(T-k) +/- c0``.

    Raises
    ------
    ValueError
        If ``n`` is below 4 (fewer recursive residuals than the statistic
        needs) or ``alpha`` is not tabulated.

    Warns
    -----
    PyardlMethodologyWarning
        When ``n`` exceeds the simulated grid. The asymptotic Kolmogorov
        approximation is then used, which widens the band slightly and so
        makes the test conservative rather than liberal.

    Notes
    -----
    Interpolation is linear in ``1/sqrt(n)``, the scale on which ``c0``
    is nearly affine, rather than in ``n`` where it is strongly convex.

    Examples
    --------
    >>> from pyardl.critical_values.bde1975 import cusumsq_c0
    >>> round(cusumsq_c0(100, 0.05), 4)
    0.1807
    """
    a = _check_alpha(alpha)
    if n < _N_MIN:
        raise ValueError(
            f"n={n} is too small: the CUSUM-of-squares statistic needs at "
            f"least {_N_MIN} recursive residuals."
        )
    if n > _N_MAX:
        from scipy.stats import kstwobign

        warnings.warn(
            f"n={n} exceeds the simulated grid (max {_N_MAX}): falling back "
            "to the asymptotic Kolmogorov approximation, which widens the "
            "band and makes the test conservative.",
            PyardlMethodologyWarning,
            stacklevel=2,
        )
        return float(kstwobign.ppf(1.0 - a)) * float(np.sqrt(2.0 / n))
    if n in _C0_TABLE:
        return _C0_TABLE[n][a]

    grid = np.asarray(C0_GRID, dtype=np.float64)
    values = np.array([_C0_TABLE[int(g)][a] for g in grid])
    # Linear in 1/sqrt(n): the grid is decreasing in that variable, so it
    # is reversed to keep np.interp's increasing-x contract.
    xs = 1.0 / np.sqrt(grid)
    order = np.argsort(xs)
    return float(np.interp(1.0 / np.sqrt(n), xs[order], values[order]))
