r"""Critical values for the DF-GLS test (Elliott, Rothenberg & Stock 1996).

Simulated in-house, and cross-checked against an independent source.

Provenance
----------
The statistic has no closed-form finite-sample distribution, so the
values are obtained by simulating the null (a Gaussian random walk),
detrending it under the local alternative, and taking the lower-tail
quantiles of the resulting statistic. 100 000 replications per grid
point, seeds recorded; see ``PROVENANCE.md``.

A second source exists for this test — the response surfaces shipped
with ``arch`` (BSD-3), themselves re-simulated by their author. The two
agree within Monte Carlo error for ``T >= 100``. At ``T = 50`` they
differ by up to 0.037, always in the same direction, and an independent
size experiment settles which is right: our values deliver 5.07% at the
nominal 5% level, the response surface 4.72%. The difference is a
fitting artefact at the edge of the surface's range, not a disagreement
about the statistic — the statistics themselves match to 1e-15. See
OBS-6 of ``docs/VALIDATION_OBSERVATIONS.md``.

References
----------
.. [1] Elliott, G., Rothenberg, T. J. & Stock, J. H. (1996). Efficient
       tests for an autoregressive unit root. *Econometrica*, 64(4),
       813-836.
"""

from __future__ import annotations

import warnings

import numpy as np

from pyardl.exceptions import PyardlMethodologyWarning

__all__ = ["dfgls_critical_values", "DFGLS_GRID"]

_ALPHAS = (0.10, 0.05, 0.01)

# --- GENERATED by validation/spec27_unitroot_cv.py - do not hand-edit ---
# n_sims=100000, seed=20260803 (+T, +7919 for 'ct'), chunk=5000.

_DFGLS_TABLE: dict[str, dict[int, dict[float, float]]] = {
    "c": {
        25: {0.1: -2.206585, 0.05: -2.516649, 0.01: -3.176067},
        30: {0.1: -2.132392, 0.05: -2.442735, 0.01: -3.082955},
        40: {0.1: -2.032614, 0.05: -2.335009, 0.01: -2.961105},
        50: {0.1: -1.959865, 0.05: -2.269620, 0.01: -2.885079},
        60: {0.1: -1.921911, 0.05: -2.223463, 0.01: -2.862954},
        70: {0.1: -1.890706, 0.05: -2.195367, 0.01: -2.820438},
        80: {0.1: -1.863120, 0.05: -2.176316, 0.01: -2.786872},
        90: {0.1: -1.836946, 0.05: -2.143893, 0.01: -2.760313},
        100: {0.1: -1.817301, 0.05: -2.130576, 0.01: -2.742120},
        120: {0.1: -1.792642, 0.05: -2.098321, 0.01: -2.709985},
        150: {0.1: -1.761976, 0.05: -2.071859, 0.01: -2.695582},
        200: {0.1: -1.727474, 0.05: -2.039788, 0.01: -2.649950},
        250: {0.1: -1.701208, 0.05: -2.017172, 0.01: -2.638885},
        300: {0.1: -1.700224, 0.05: -2.017542, 0.01: -2.627181},
        400: {0.1: -1.683272, 0.05: -2.000960, 0.01: -2.615054},
        500: {0.1: -1.656238, 0.05: -1.971378, 0.01: -2.591254},
        700: {0.1: -1.652827, 0.05: -1.969351, 0.01: -2.603210},
        1000: {0.1: -1.639755, 0.05: -1.961633, 0.01: -2.583322},
        2000: {0.1: -1.631559, 0.05: -1.948298, 0.01: -2.562744},
    },
    "ct": {
        25: {0.1: -3.153802, 0.05: -3.491050, 0.01: -4.210397},
        30: {0.1: -3.073123, 0.05: -3.399823, 0.01: -4.091913},
        40: {0.1: -2.955420, 0.05: -3.266189, 0.01: -3.891280},
        50: {0.1: -2.883486, 0.05: -3.186869, 0.01: -3.799907},
        60: {0.1: -2.829517, 0.05: -3.130007, 0.01: -3.712960},
        70: {0.1: -2.790191, 0.05: -3.082376, 0.01: -3.685736},
        80: {0.1: -2.768106, 0.05: -3.056989, 0.01: -3.656168},
        90: {0.1: -2.745675, 0.05: -3.047721, 0.01: -3.626461},
        100: {0.1: -2.730655, 0.05: -3.019426, 0.01: -3.607029},
        120: {0.1: -2.707199, 0.05: -3.003144, 0.01: -3.570848},
        150: {0.1: -2.677500, 0.05: -2.970192, 0.01: -3.545264},
        200: {0.1: -2.649426, 0.05: -2.938990, 0.01: -3.514174},
        250: {0.1: -2.625683, 0.05: -2.909864, 0.01: -3.475158},
        300: {0.1: -2.618786, 0.05: -2.904414, 0.01: -3.484794},
        400: {0.1: -2.604915, 0.05: -2.897517, 0.01: -3.452929},
        500: {0.1: -2.596947, 0.05: -2.884140, 0.01: -3.446356},
        700: {0.1: -2.590345, 0.05: -2.876217, 0.01: -3.438684},
        1000: {0.1: -2.570777, 0.05: -2.859112, 0.01: -3.416693},
        2000: {0.1: -2.562524, 0.05: -2.847826, 0.01: -3.415976},
    },
}


#: Sample sizes covered, per trend.
DFGLS_GRID: tuple[int, ...] = tuple(sorted(_DFGLS_TABLE["c"]))


def _interp(table: dict[int, dict[float, float]], n: int, alpha: float) -> float:
    """Interpolate linearly in ``1/n``, where the curve is nearly affine."""
    grid = np.array(sorted(table), dtype=np.float64)
    values = np.array([table[int(g)][alpha] for g in grid])
    xs = 1.0 / grid
    order = np.argsort(xs)
    return float(np.interp(1.0 / n, xs[order], values[order]))


def dfgls_critical_values(nobs: int, trend: str = "c") -> dict[float, float]:
    """Left-tail critical values of the DF-GLS statistic.

    Parameters
    ----------
    nobs : int
        Length of the series tested. This is ``len(y)``, not the number
        of rows of the ADF regression: the asymptotics are in the sample
        size, and that is the axis the table was simulated on.
    trend : {'c', 'ct'}, default 'c'

    Returns
    -------
    dict
        Level to critical value, at 10%, 5% and 1%.

    Warns
    -----
    PyardlMethodologyWarning
        When ``nobs`` falls outside the simulated grid; the nearest
        endpoint is then used.

    Examples
    --------
    >>> from pyardl.critical_values.ers1996 import dfgls_critical_values
    >>> cv = dfgls_critical_values(200, "c")
    >>> round(cv[0.05], 3)
    -2.04
    """
    if trend not in _DFGLS_TABLE:
        raise ValueError(f"trend={trend!r} must be 'c' or 'ct'.")
    table = _DFGLS_TABLE[trend]
    lo, hi = min(table), max(table)
    if nobs < lo or nobs > hi:
        warnings.warn(
            f"nobs={nobs} is outside the simulated grid [{lo}, {hi}]: the "
            "nearest endpoint is used. Below the grid the test is severely "
            "under-powered anyway; above it the asymptotic values apply.",
            PyardlMethodologyWarning,
            stacklevel=2,
        )
        nobs = min(max(nobs, lo), hi)
    return {a: _interp(table, nobs, a) for a in _ALPHAS}
